### ISSUE TITLE
Error in building ClevoControl.kext

### ISSUE THREAD

**Issue by JesseVelden** [datasone/ClevoControl#2]
I get an error trying to build ClevoControl.kext.   
On [line 64 of ClevoControl.cpp](https://github.com/datasone/ClevoControl/blob/292d22635904d5cca211591f8d616ccfe455a845/ClevoControl/ClevoControl.cpp#L64) I get an error: `Too few arguments provided to function-like macro invocation`. Maybe some weird Xcode behaviour?

**Comment by datasone** [comment]
Thanks for putting up this, it seems Apple deprecated `strcpy` (maybe in 10.13? I don't know) , so now using `strlcpy` instead.
Fixed in f0ccc5ef58f5304c9a07b4e3d2108b76997e3492.
