### ISSUE TITLE
Cannot launch ClevoKBFanControl

### ISSUE THREAD

**Issue by alwzying** [datasone/ClevoControl#4]
command not found

**Comment by datasone** [comment]
I think you may execute `./ClevoKBFanControl` in directory contains it or copy the program into a directory in the `PATH` environment variable.

**Comment by alwzying** [comment]
It's strange that when I use Safari on macOS to download it, it has an extension: dms and cannot work. When I use Chrome on Windows 10 to download it, it seems normal.
