### ISSUE TITLE
New Clevo kext for keyboard backlighting & fan

### ISSUE THREAD

**Issue by FreeJHack** [datasone/ClevoControl#7]
I wrote a new kext for changing the keyboard backlighting direct from the key pad (as in Windows) with boot & sleep/wake automatic restoring.
Take a look at https://github.com/FreeJHack/ClevoService
Maybe could be interesting for someone...
Cheers

**Comment by datasone** [comment]
Thanks for the kext! I've added link to your project in the README. (Actually I'm not using Clevo laptops as Hackintosh any more so I took this as an awesome replacement 😂)

**Comment by FreeJHack** [comment]
Ok.
Thanks.
